import assert from 'node:assert/strict'
import { mkdtemp, mkdir, readFile, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'
import { evaluateChangeWindowManifest, inspectChangeWindowManifestJson, sha256, verifyChangeWindowManifest } from '../lib/change-window-proof.mjs'
import { fixture, reseal } from './helpers.mjs'

const evaluated = async (mutate, seal = true) => { const manifest = await fixture(); mutate?.(manifest); if (seal) reseal(manifest); return evaluateChangeWindowManifest(manifest) }

test('verifies a complete change-window settlement', async () => { const result = await evaluated(); assert.equal(result.verdict, 'window-compliant'); assert.deepEqual(Object.values(result.checks), Array(10).fill(true)) })
test('inspection is bounded and redacted', async () => { const manifest = reseal(await fixture()); const result = inspectChangeWindowManifestJson(JSON.stringify(manifest)); assert.equal(result.windowCount, 2); assert.equal(result.eventCount, 3); assert.equal(JSON.stringify(result).includes(manifest.proofId), false) })
test('rejects a sequence gap', async () => { const manifest = await fixture(); manifest.events[1].sequence = 7; assert.throws(() => evaluateChangeWindowManifest(manifest), { code: 'INVALID_MANIFEST' }) })
test('detects a broken previous-event link', async () => { const result = await evaluated(manifest => { reseal(manifest); manifest.events[1].previousEventSha256 = 'f'.repeat(64) }, false); assert.equal(result.checks.hashChainValid, false) })
test('detects a forged event hash', async () => { const result = await evaluated(manifest => { reseal(manifest); manifest.events[1].eventSha256 = 'f'.repeat(64) }, false); assert.equal(result.checks.hashChainValid, false) })
test('detects a mismatched ledger head', async () => { const result = await evaluated(manifest => { reseal(manifest); manifest.settlement.ledgerHeadSha256 = 'f'.repeat(64) }, false); assert.equal(result.checks.hashChainValid, false) })
test('detects an undeclared window', async () => { const result = await evaluated(manifest => { manifest.settlement.declaredWindowIdHash = 'f'.repeat(64); for (const event of manifest.events) event.windowIdHash = 'f'.repeat(64) }); assert.equal(result.checks.declaredWindowExists, false); assert.equal(result.verdict, 'not-window-compliant') })
test('detects artifact environment and receipt binding drift', async () => { const result = await evaluated(manifest => { manifest.events[1].artifactSha256 = 'f'.repeat(64) }); assert.equal(result.checks.bindingsSatisfied, false) })
test('detects a start before the window', async () => { const result = await evaluated(manifest => { manifest.settlement.startedAt = manifest.events[0].occurredAt = '2026-08-26T07:59:00.000Z' }); assert.equal(result.checks.windowSatisfied, false) })
test('detects completion after the window', async () => { const result = await evaluated(manifest => { manifest.settlement.completedAt = manifest.events[2].occurredAt = '2026-08-26T10:01:00.000Z' }); assert.equal(result.checks.windowSatisfied, false) })
test('enforces the no-new-step cutoff', async () => { const result = await evaluated(manifest => { manifest.events[1].occurredAt = '2026-08-26T09:50:00.000Z' }); assert.equal(result.checks.cutoffSatisfied, false) })
test('enforces maximum duration', async () => { const result = await evaluated(manifest => { manifest.policy.maxDurationMs = 3600000; manifest.settlement.completedAt = manifest.events[2].occurredAt = '2026-08-26T09:20:00.000Z' }); assert.equal(result.checks.durationSatisfied, false) })
test('enforces distinct observers', async () => { const result = await evaluated(manifest => { for (const event of manifest.events) event.observerHash = 'a'.repeat(64) }); assert.equal(result.checks.observerThresholdSatisfied, false) })
test('detects stale evidence', async () => { const result = await evaluated(manifest => { manifest.evaluationTime = '2026-08-28T10:30:00.000Z' }); assert.equal(result.checks.evidenceFresh, false) })
test('rejects secret-shaped and raw fields', async () => { const manifest = await fixture(); manifest.raw = 'deployment output'; assert.throws(() => evaluateChangeWindowManifest(manifest), { code: 'SECRET_MATERIAL' }); const second = await fixture(); second.note = 'Bearer abcdefghijklmnopqrstuvwxyz'; assert.throws(() => evaluateChangeWindowManifest(second), { code: 'SECRET_MATERIAL' }) })
test('writes deterministic content-addressed evidence and verifies replay', async () => { const root = await mkdtemp(join(tmpdir(), 'dsh-change-window-')); await mkdir(join(root, 'input')); const manifest = reseal(await fixture()); await writeFile(join(root, 'input', 'manifest.json'), JSON.stringify(manifest)); const first = await verifyChangeWindowManifest({ workspaceRoot: root, manifestPath: 'input/manifest.json', artifactDir: 'artifacts' }); const second = await verifyChangeWindowManifest({ workspaceRoot: root, manifestPath: 'input/manifest.json', artifactDir: 'artifacts' }); assert.equal(first.artifact.sha256, second.artifact.sha256); assert.equal(first.artifact.verifiedByReadBack, true); assert.equal(sha256(await readFile(join(root, first.artifact.path))), first.artifact.sha256) })
test('rejects path traversal and symlinked artifact directories', async t => { const root = await mkdtemp(join(tmpdir(), 'dsh-change-window-safe-')); await mkdir(join(root, 'input')); await writeFile(join(root, 'input', 'manifest.json'), JSON.stringify(reseal(await fixture()))); await assert.rejects(verifyChangeWindowManifest({ workspaceRoot: root, manifestPath: '../manifest.json', artifactDir: 'artifacts' }), { code: 'PATH_ESCAPE' }); const outside = await mkdtemp(join(tmpdir(), 'dsh-change-window-outside-')); try { await symlink(outside, join(root, 'linked'), process.platform === 'win32' ? 'junction' : 'dir') } catch (error) { t.skip(`symlinks unavailable: ${error.code}`); return } await assert.rejects(verifyChangeWindowManifest({ workspaceRoot: root, manifestPath: 'input/manifest.json', artifactDir: 'linked' }), { code: 'UNSAFE_ARTIFACT_DIR' }) })
